[package]
name = "rust_option_pricer"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <you@example.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
statrs="0.15.0"
